Consider CA cert when we create a Service Client
gophercloud/utils pull request #131
Opened 2020-12-02 11:11 UTC by Fedosin

Now, when we create a service client with gophercloud/utils, cacert[1] option is ignored, which leads to the fact that we can't work with self-signed certificates out of the box. Also it creates inconsistencies with python-openstackclient, where "cacert" option matters.

To remove the discrepancy this commit implements full cacert support.

[1] https://github.com/gophercloud/utils/blob/88c6e9e533261350ec733e2e2147a1d3f8eb62de/openstack/clientconfig/results.go#L39-L41

2020-12-02 12:51 UTC, kayrus requested changes
The code is similar to https://github.com/gophercloud/utils/blob/8677e053dcf1f05d0fa0a616094aace04690eb94/terraform/auth/config.go#L164-L174

I suggest to put the logic into one place with an ability to reuse it.

2020-12-02 12:51 UTC, kayrus commented on openstack/clientconfig/requests.go
> +		caCert = string(bytes.TrimSpace(caFile))
You're converting bytes to a string, then convert a string to bytes on the line 784. Can you define the `caCert` var as `[]byte` initially?

2020-12-02 14:47 UTC, Fedosin commented
@kayrus hi! thank you for you comments. I reused the code from the Terraform client as you suggested :)

2020-12-03 06:53 UTC, jtopjian approved these changes
This looks good to me. I'll wait for @kayrus to confirm before merging.

2020-12-03 07:03 UTC, kayrus requested changes
Overall good, except the type conversion

2020-12-03 07:03 UTC, kayrus commented on internal/util.go
> +			return string(contents), true, err
can you return `[]byte` in this func? this will allow to avoid excessive `string` -> `[]byte` conversion

2020-12-03 13:57 UTC, Fedosin commented on internal/util.go
> +			return string(contents), true, err
yes, sure! this conversion is absolutely unnecessary

2020-12-03 14:16 UTC, kayrus approved these changes
LGTM, thanks

2020-12-03 16:14 UTC, jtopjian commented
@Fedosin Thank you for working on this. @kayrus Thank you for the review.

2020-12-03 16:14 UTC, merged